# Generated by Django 5.1.2 on 2025-04-14 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_order_session_table_customerrequest_orderitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="session_id",
        ),
        migrations.AlterField(
            model_name="session",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
