# Generated by Django 4.2.3 on 2025-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_session_session_id_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='request_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
