# Generated by Django 4.2.3 on 2025-05-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_zone_table_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.orderitem')),
            ],
        ),
    ]
