# Generated by Django 4.2.3 on 2025-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_kitchenevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cook_time_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='public_id',
            field=models.UUIDField(null=True),
        ),
    ]
