# Generated by Django 4.2.3 on 2025-05-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_menuitem_cook_time_min_menuitem_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('cooking', 'Cooking'), ('ready', 'Ready')], default='queued', max_length=10)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('eta_finish_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_events', to='backend.orderitem')),
            ],
            options={
                'ordering': ['eta_finish_at'],
            },
        ),
    ]
